defaults:
  - env/train: omnigibson_r1pro_behavior
  - env/eval: omnigibson_r1pro_behavior
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null 
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/
    
cluster:
  num_nodes: 1
  component_placement:
    actor: 0-1
    env, rollout: 2-3

runner:
  task_type: embodied
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "test_openvla"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 1000
  max_steps: -1

  only_eval: False
  val_check_interval: -1
  save_interval: 40
  seq_length: 4096
  max_prompt_length: 50

algorithm:
  auto_reset: False
  ignore_terminations: False
  use_fixed_reset_state_ids: False
  normalize_advantages: True
  kl_penalty: kl  # how to estimate kl divergence: kl or kl_penalty
  group_size: 1
  n_chunk_steps: 200
  n_eval_chunk_steps: 200
  num_group_envs: 2
  rollout_epoch: 8
  reward_type: chunk_level
  logprob_type: token_level
  entropy_type: token_level

  adv_type: embodied_gae
  loss_type: embodied_ppo
  loss_agg_func: "token-mean"
  kl_beta: 0.0
  entropy_bonus: 0
  clip_ratio_high: 0.28
  clip_ratio_low: 0.2
  clip_ratio_c: 3.0
  value_clip: 0.2
  huber_delta: 10.0


  gamma: 0.99
  gae_lambda: 0.95

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature_train: 1.0
    temperature_eval: 0.6
    top_k: 50
    top_p: 1.0
    repetition_penalty: 1.0

  # length argument for autoregressive sampling
  # max length means max amount of tokens to generate
  length_params:
    max_new_token: null
    max_length: 1024
    min_length: 1

env:
  group_name: "EnvGroup"
  channel:
    name: "env_buffer_list"
    queue_name: "obs_buffer"
    queue_size: 0
  enable_offload: False

  num_envs_per_gpu: 2

rollout:
  group_name: "RolloutGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "action_buffer"
    queue_size: 0
  mode: "colocate"
  backend: "huggingface"
  model_dir: "/mnt/mnt/public/mjwei/download_models/openvla/openvla-7b-finetuned-behavior-1k/openvla-7b+behavior_turn_on_radio+b4+lr-0.0005+lora-r32+dropout-0.0--image_aug--sft_behavior_turn_on_radio-nohead-bs4-rgb_image-lr5e-4-lorarank32--10000_chkpt"
  enable_offload: True
  pipeline_stage_num: 1

actor:
  group_name: "ActorGroup"
  channel:
    name: ${env.channel.name}
    queue_name: "replay_buffer"
    queue_size: 0
  training_backend: "fsdp"
  checkpoint_load_path: "/mnt/mnt/public/mjwei/download_models/openvla/openvla-7b-finetuned-behavior-1k/openvla-7b+behavior_turn_on_radio+b4+lr-0.0005+lora-r32+dropout-0.0--image_aug--sft_behavior_turn_on_radio-nohead-bs4-rgb_image-lr5e-4-lorarank32--10000_chkpt"
  checkpoint_save_path: "../results"
  micro_batch_size: 2
  global_batch_size: 160
  seed: 1234
  enable_offload: True

  model:
    model_name: "openpi"
    precision: null
    num_action_chunks: 5 # interface for the env
    action_dim: 7
    is_lora: False
    use_wrist_image: True
    use_proprio: True
    num_steps: 4
    sharding_strategy: "no_shard"
    # openpi specific parameters
    openpi:
      noise_level: 0.5
      action_chunk: ${actor.model.num_action_chunks}
      num_steps: ${actor.model.num_steps}
      train_expert_only: True
      action_env_dim: ${actor.model.action_dim}
      noise_method: "flow_sde" 
      add_value_head: True
      detach_critic_input: True

  optim:
    lr: 1.0e-4
    value_lr: 3.0e-3
    adam_beta1: 0.9
    adam_beta2: 0.999
    adam_eps: 1.0e-05
    clip_grad: 10.0

  tokenizer:
    tokenizer_type: "HuggingFaceTokenizer"
    tokenizer_model: "/mnt/mnt/public/mjwei/download_models/openvla/openvla-7b-finetuned-behavior-1k/openvla-7b+behavior_turn_on_radio+b4+lr-0.0005+lora-r32+dropout-0.0--image_aug--sft_behavior_turn_on_radio-nohead-bs4-rgb_image-lr5e-4-lorarank32--10000_chkpt"
    use_fast: False
    trust_remote_code: True
    padding_side: "right"

reward:
  use_reward_model: False

critic:
  use_critic_model: False