defaults:
  - env/realworld_dex_pnp@env.eval
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    env:
      node_group: franka
      placement: 0
  node_groups:
    - label: franka
      node_ranks: 0
      hardware:
        type: Franka
        configs:
          - robot_ip: 172.16.0.2
            node_rank: 0

runner:
  task_type: embodied
  logger:
    log_path: null
    project_name: rlinf
    experiment_name: "collect-dexpnp-demo"
    logger_backends: ["tensorboard"]
  num_data_episodes: 20       # 目标成功 demo 数量
  record_task_description: False

env:
  group_name: "EnvGroup"
  eval:
    ignore_terminations: False  # 让分类器触发的 termination 生效
    auto_reset: False           # 由 collector 控制 reset
    no_gripper: False
    use_spacemouse: True
    glove_config:
      left_port: "/dev/ttyACM0"
      frequency: 30
    classifier_reward_wrapper:
      checkpoint_path: "/workspace/RLinf/logs/20260303-04:41:36-reward-classifier-dex_pnp/reward_classifier.pt"
      image_keys: ["wrist_1"]
      device: cpu               # 控制节点无 GPU，用 CPU 推理
      threshold: 0.75
    override_cfg:
      target_ee_pose: [0.8188, 0.1384, 0.1188, -3.1331, -1.1213, -0.0676]
      end_effector_type: "ruiyan_hand"
      end_effector_config:
        port: "/dev/ttyUSB0"
        baudrate: 460800
        motor_ids: [1, 2, 3, 4, 5, 6]
        default_velocity: 2000
        default_current: 800
        default_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      hand_target_state: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      hand_reset_state: [0.4, 0.0, 0.0, 0.0, 0.0, 0.0]
      hand_action_scale: 1.0
      joint_reset_qpos: [0, 0, 0, -1.9, 0, 2, 0]
      use_dense_reward: False
      is_dummy: False
