defaults:
  - qwen2.5-1.5b-grpo-fsdp
  - _self_

runner:
  experiment_name: gspo-1.5b
  enable_dynamic_batch_size: False
  seq_length: 2048

algorithm:
  loss_type: gspo
  adv_type: grpo
  loss_agg_func: seq-mean-token-mean
  normalize_advantages: False
  use_valid_token_scale: False
  importance_sampling_fix: False
  clip_ratio_low: 0.0003
  clip_ratio_high: 0.0004
  clip_ratio_c: null
  group_size: 4
  n_minibatches: 2
  training_batch_size_per_gpu: 1
  logprob_forward_micro_batch_size: ${algorithm.training_batch_size_per_gpu}

data:
  rollout_batch_size: 16
  max_prompt_length: 512

rollout:
  model:
    model_path: ${actor.model.model_path}
    precision: bf16

actor:
  model:
    precision: fp32
  tokenizer:
    tokenizer_model: ${actor.model.model_path}
  fsdp_config:
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
    amp_autocast:
      enabled: False
    grad_scaler:
      enabled: False
