name: Bug report
description: Raise an issue here if you find a bug.
title: "[Bug]: "
labels: ["bug"]

body:
- type: textarea
  attributes:
    label: Affected component
    description: |
      *What* is affected by this bug?
  validations:
    required: true
- type: textarea
  attributes:
    label: Bug description
    description: |
      Please provide a clear and concise description of what the bug is.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      Please provide the environment you are using via the following command:
      ```
      python -V
      pip list | grep -E "torch|sglang|vllm|ray|transformers"
      nvidia-smi
      ```
      Additionally, please provide the RLinf version, Megatron version if you are using Megatron, and docker image version if you are using our images
    value: |
      Python version:
      PIP list:
      RLinf version: 
      Megatron version: 
      Docker image version: 
      nvidia-smi:
  validations:
    required: true
- type: textarea
  attributes:
    label: Reproduction
    description: |
      Please describe how could we reproduce the issue. If applicable, you can provide a minimal code snippet or steps to reproduce the issue.
  validations:
    required: true
- type: markdown
  attributes:
    value: >
      Thanks for contributing to RLinf!
- type: checkboxes
  id: check_doc
  attributes:
    label: Before submitting a new issue...
    options:
      - label: Have you checked relevant issues, FAQs (https://rlinf-docs.readthedocs.io/en/latest/rst_source/faq.html), or asked the chatbot at the top right corner of the [documentation page](https://rlinf-docs.readthedocs.io).
        required: true