simulator_type: libero
task_suite_name: libero_goal

auto_reset: true
ignore_terminations: true
max_episode_steps: 512

use_rel_reward: true
reward_coef: 5.0
only_eval: true

seed: 0
num_group: ${env.eval.num_envs}
group_size: 1
use_fixed_reset_state_ids: True
num_images_in_input: 1

num_envs: 500

video_cfg:
  save_video: true
  info_on_video: true
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 256
  camera_widths: 256