# Usage:
#   ALOHA_SANDWICH_VALUE_CHECKPOINT=/abs/path/to/value/checkpoint \
#   bash examples/offline_rl/advantage_labeling/recap/process/run_compute_advantages.sh aloha_sandwich_recap_compute_advantages --nproc 1

defaults:
  - model/recap_value_model@advantage.model

advantage:
  value_checkpoint: ${oc.env:ALOHA_SANDWICH_VALUE_CHECKPOINT}
  batch_size: 1024
  flush_interval: 256
  num_dataloader_workers_per_gpu: 12
  prefetch_factor: 2
  discount_next_value: true
  positive_quantile: 0.3
  tag: sandwich_fail300_N10_q30_teleop
  returns_tag: sandwich_fail300

  model:
    critic_expert_variant: "gemma_1m"
    tokenizer_path: /inspire/hdd/project/robot-reasoning/public/shared/hf-models/google/gemma-3-270m
    siglip_path: /inspire/hdd/project/robot-reasoning/public/shared/hf-models/google/siglip2-so400m-patch14-224
    gemma3_path: /inspire/hdd/project/robot-reasoning/public/shared/hf-models/google/gemma-3-270m

data:
  model_type: pi05

  train_data_paths:
    - dataset_path: /inspire/qb-ilm/project/robot-reasoning/czxs253130583/yushun/aloha-data/sandwich_lerobot_v21
      robot_type: aloha
      type: rollout
      weight: 1.0

  advantage_lookahead_step: 16
  gamma: 1.0

distributed:
  enabled: true
  backend: "nccl"
  timeout: 3600

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:REPO_PATH}/examples/offline_rl/config/
  job:
    chdir: false
