model_type: "molmoact2"

# model path
model_path: "/path/to/models/MolmoAct2-LIBERO"

precision: "fp32"
max_prompt_length: 128

# action settings
action_dim: 7
num_action_chunks: 1

# MolmoAct2 inference settings
num_steps: 10
inference_action_mode: "continuous"
discrete_action_tokenizer: "allenai/MolmoAct2-FAST-Tokenizer"
enable_depth_reasoning: false
norm_tag: "libero"

# loading settings
is_lora: false
load_to_device: true
trust_remote_code: true
