# RStar2 工具配置示例
# 此配置文件展示了如何配置工具以避免Ray序列化错误

# 方式1: 使用配置对象（在训练配置文件中添加）
# 将以下内容添加到您的训练配置文件（例如 config.yaml）中：

tools:
  code_judge:
    host_addr: "localhost"
    host_port: 8088
    batch_size: 4
    concurrency: 2
    batch_timeout_seconds: 30.0
    enable_jupyter: false  # 如果需要jupyter工具，设置为true

# 方式2: 使用独立的工具配置文件
# 在训练配置中指定工具配置文件路径：

# rollout:
#   tool_config_path: "toolkits/rstar2/tools/tool_config/python_tool_config.yaml"

# 或者在顶级配置中：
# tool_config_path: "toolkits/rstar2/tools/tool_config/python_tool_config.yaml"

