name: Math Auto Placement

on:
    push:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

    pull_request:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '*.yaml'
          - '*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    qwen-grpo-test:
        runs-on: reason

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: auto-placement
              timeout-minutes: 20
              run: |
                export REPO_PATH=$(pwd)
                source switch_env reason
                bash tests/e2e_tests/auto_placement/run_auto_placement.sh