name: Coding Online RL End2End

on:
    push:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

    pull_request:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '*.yaml'
          - '*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    qwen-ppo-test:
        runs-on: reason

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install dependencies
              run: |
                pip install httpx asyncio fuzzywuzzy

            - name: SGLang Collocated mode
              run: |
                export REPO_PATH=$(pwd)
                bash tests/e2e_tests/coding_online_rl/run_coding_online_rl.sh
