name: Embodied End2End

on:
    push:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

    pull_request:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    openvla-ppo-test:
        runs-on: embodied

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: OpenVLA test
              timeout-minutes: 20
              run: |
                export REPO_PATH=$(pwd)
                bash tests/e2e_tests/embodied/run_openvla.sh
    openvlaoft-grpo-test:
        runs-on: embodied

        steps:
            - name: Checkout code
              uses: actions/checkout@v5
            - name: OpenVLA-OFT test
              run: |
                export REPO_PATH=$(pwd)
                bash tests/e2e_tests/embodied/run_openvlaoft_libero130.sh