name: Lint

on:
    push:
        branches: [ main, feat/*, v* ]
    pull_request:
        branches: [ main, feat/*, v* ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    lint:
        runs-on: self-hosted
        container:
            image: beijing-j.cr.infini-ai.com:32443/te-dbdcudoygepmq5vx/rlsys:v2.4
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: Install ruff
              run: pip install ruff
              
            - name: Run ruff linter
              run: ruff check .
              
            - name: Run ruff formatter check
              run: ruff format --check .