name: Unit Tests

on:
    push:
        branches:
          - 'v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'

    pull_request:
        branches:
          - 'v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '*.yaml'
          - '*.toml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    unit-tests-cuda:
        runs-on: reason

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install pytest
              run: |
                source switch_env reason
                uv pip install pytest

            - name: Run pytest
              timeout-minutes: 20
              run: |
                export PYTHONPATH=$(pwd):$(pwd)/megatron:$(pwd)/tests/unit_tests
                source switch_env reason
                pytest tests/unit_tests
            
            - name: Run doctest
              timeout-minutes: 20
              run: |
                source switch_env reason
                pytest --doctest-modules rlinf/scheduler
      
    unit-tests-cpu:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install dependencies
              run: |
                pip install uv
                uv venv
                source .venv/bin/activate
                UV_TORCH_BACKEND=auto uv sync
                uv pip install pytest

            - name: Run pytest
              timeout-minutes: 20
              run: |
                export PYTHONPATH=$(pwd):$(pwd)/megatron:$(pwd)/tests/unit_tests 
                source .venv/bin/activate
                pytest tests/unit_tests