name: Unit Tests

on:
    push:
        branches:
          - 'v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'

    pull_request:
        branches:
          - 'v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '*.yaml'
          - '*.toml'

permissions:
  contents: read

jobs:
    unit-tests-cuda:
        runs-on: reason

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install pytest
              run: pip install pytest

            - name: Run pytest
              timeout-minutes: 20
              run: |
                export PYTHONPATH=$(pwd):$(pwd)/megatron:$(pwd)/tests/unit_tests 
                pytest tests/unit_tests
            
            - name: Run doctest
              timeout-minutes: 20
              run: |
                pytest --doctest-modules rlinf/scheduler
      
    unit-tests-cpu:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Install dependencies
              run: pip install pytest torch==2.6.0 torchvision torchaudio ray hydra-core==1.4.0.dev1 numpy

            - name: Run pytest
              timeout-minutes: 20
              run: |
                export PYTHONPATH=$(pwd):$(pwd)/megatron:$(pwd)/tests/unit_tests 
                pytest tests/unit_tests