name: Unit Tests

on:
    push:
        branches:
          - 'v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'

    pull_request:
        branches:
          - 'v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '*.yaml'
          - '*.toml'

permissions:
  contents: read

jobs:
    unit-tests-cuda:
        runs-on: reason
        container:
            image: rlinf/rlinf:math-rlinf0.1-torch2.6.0-sglang0.4.6.post5-vllm0.8.5-megatron0.13.0-te2.1
            volumes:
                - /mnt/public/dataset:/workspace/dataset
                - /mnt/public/tokenizer:/workspace/tokenizer
            options: --gpus="all" --shm-size=80g

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pytest
              run: pip install pytest

            - name: Run pytest
              timeout-minutes: 20
              run: |
                export PYTHONPATH=$(pwd):$(pwd)/megatron:$(pwd)/tests/unit_tests 
                pytest tests/unit_tests
            
            - name: Run doctest
              timeout-minutes: 20
              run: |
                pytest --doctest-modules rlinf/scheduler
      
    unit-tests-cpu:
        runs-on: ubuntu-latest
        container:
            image: rlinf/rlinf:math-rlinf0.1-torch2.6.0-sglang0.4.6.post5-vllm0.8.5-megatron0.13.0-te2.1

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install pytest
              run: pip install pytest

            - name: Run pytest
              timeout-minutes: 20
              run: |
                export PYTHONPATH=$(pwd):$(pwd)/megatron:$(pwd)/tests/unit_tests 
                pytest tests/unit_tests